# Generated by Django 4.0.2 on 2022-02-22 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urls',
            options={'verbose_name_plural': 'Urls'},
        ),
        migrations.AlterField(
            model_name='urls',
            name='uuid',
            field=models.CharField(max_length=10),
        ),
    ]
